package com.nhom15.drawguess.common.protocol;

public enum MessageType {

    // Test
    PING,
    PONG,

    // Register
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILED,

    // Authentication
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    ACTION_SUCCESS,
    ACTION_FAILED,

    // Rooms
    GET_ROOMS,
    ROOM_LIST,
    JOIN_ROOM,
    JOIN_SUCCESS,
    JOIN_FAILED,
    LEAVE_ROOM,
    ROOM_INFO,
    READY,
    CANCEL_READY,
    READY_STATUS,
    GAME_STARTING,
    START_GAME,

    ROUND_CATEGORY,
    DRAW_WORD,
    SUBMIT_DRAW,
    DRAW_UPLOAD,
    ROUND_START,
    GUESS,
    GUESS_RESULT,
    SCORE_UPDATE,
    TIME_UPDATE,
    TIME_UP,
    ANSWER,
    GAME_END,
    GAME_RESULT,
    GET_HISTORY, HISTORY_LIST, GET_HISTORY_DETAIL, HISTORY_DETAIL, HISTORY_FAILED,
    GET_HISTORY_IMAGE, HISTORY_IMAGE, HISTORY_IMAGE_FAILED,
    GET_CATALOG, CATALOG, EDIT_CATALOG, CATALOG_SAVED, CATALOG_FAILED,
    GAME_ERROR
}
